module Model.CustomMaze where

import Model.Maze

import qualified Data.Map as Map

-- generated using:
-- python .\scripts\mazebuilder_v2.py .\scripts\data\maze_assymetric.txt -m Model.CustomMaze -o .\src\Model\CustomMaze.hs -i Model.Maze -v
customMaze :: Maze
customMaze = foldr f Map.empty xs
 where 
  f (k, v) = Map.insert k v
  xs = 
    [ ((0, 0), MkWall (MkCorner SE))
    , ((1, 0), MkWall (MkWallShape Horizontal))
    , ((2, 0), MkWall (MkWallShape Horizontal))
    , ((3, 0), MkWall (MkWallShape Horizontal))
    , ((4, 0), MkWall (MkWallShape Horizontal))
    , ((5, 0), MkWall (MkWallShape Horizontal))
    , ((6, 0), MkWall (MkWallShape Horizontal))
    , ((7, 0), MkWall (MkWallShape Horizontal))
    , ((8, 0), MkWall (MkWallShape Horizontal))
    , ((9, 0), MkWall (MkWallShape Horizontal))
    , ((10, 0), MkWall (MkWallShape Horizontal))
    , ((11, 0), MkWall (MkCorner SW))
    , ((0, 1), MkWall (MkWallShape Vertical))
    , ((1, 1), MkWall (MkCorner SE))
    , ((2, 1), MkWall (MkWallShape Horizontal))
    , ((3, 1), MkWall (MkWallShape Horizontal))
    , ((4, 1), MkWall (MkCorner SW))
    , ((5, 1), MkWall (MkCorner SE))
    , ((6, 1), MkWall (MkWallShape Horizontal))
    , ((7, 1), MkWall (MkWallShape Horizontal))
    , ((8, 1), MkWall (MkWallShape Horizontal))
    , ((9, 1), MkWall (MkWallShape Horizontal))
    , ((10, 1), MkWall (MkCorner SW))
    , ((11, 1), MkWall (MkWallShape Vertical))
    , ((0, 2), MkWall (MkWallShape Vertical))
    , ((1, 2), MkWall (MkWallShape Vertical))
    , ((2, 2), MkFloor EmptyTile)
    , ((3, 2), MkFloor EmptyTile)
    , ((4, 2), MkWall (MkWallShape Vertical))
    , ((5, 2), MkWall (MkWallShape Vertical))
    , ((6, 2), MkFloor EmptyTile)
    , ((7, 2), MkFloor EmptyTile)
    , ((8, 2), MkFloor EmptyTile)
    , ((9, 2), MkFloor EmptyTile)
    , ((10, 2), MkWall (MkWallShape Vertical))
    , ((11, 2), MkWall (MkWallShape Vertical))
    , ((0, 3), MkWall (MkWallShape Vertical))
    , ((1, 3), MkWall (MkWallShape Vertical))
    , ((2, 3), MkFloor EmptyTile)
    , ((3, 3), MkFloor EmptyTile)
    , ((4, 3), MkWall (MkCorner NE))
    , ((5, 3), MkWall (MkCorner NW))
    , ((6, 3), MkFloor EmptyTile)
    , ((7, 3), MkFloor EmptyTile)
    , ((8, 3), MkFloor EmptyTile)
    , ((9, 3), MkFloor EmptyTile)
    , ((10, 3), MkWall (MkWallShape Vertical))
    , ((11, 3), MkWall (MkWallShape Vertical))
    , ((0, 4), MkWall (MkWallShape Vertical))
    , ((1, 4), MkWall (MkWallShape Vertical))
    , ((2, 4), MkFloor EmptyTile)
    , ((3, 4), MkFloor EmptyTile)
    , ((4, 4), MkFloor EmptyTile)
    , ((5, 4), MkFloor EmptyTile)
    , ((6, 4), MkFloor EmptyTile)
    , ((7, 4), MkFloor EmptyTile)
    , ((8, 4), MkFloor EmptyTile)
    , ((9, 4), MkFloor EmptyTile)
    , ((10, 4), MkWall (MkWallShape Vertical))
    , ((11, 4), MkWall (MkWallShape Vertical))
    , ((0, 5), MkWall (MkWallShape Vertical))
    , ((1, 5), MkWall (MkCorner NE))
    , ((2, 5), MkWall (MkWallShape Horizontal))
    , ((3, 5), MkWall (MkWallShape Horizontal))
    , ((4, 5), MkWall (MkWallShape Horizontal))
    , ((5, 5), MkWall (MkWallShape Horizontal))
    , ((6, 5), MkWall (MkWallShape Horizontal))
    , ((7, 5), MkWall (MkWallShape Horizontal))
    , ((8, 5), MkWall (MkWallShape Horizontal))
    , ((9, 5), MkWall (MkWallShape Horizontal))
    , ((10, 5), MkWall (MkCorner NW))
    , ((11, 5), MkWall (MkWallShape Vertical))
    , ((0, 6), MkWall (MkCorner NE))
    , ((1, 6), MkWall (MkWallShape Horizontal))
    , ((2, 6), MkWall (MkWallShape Horizontal))
    , ((3, 6), MkWall (MkWallShape Horizontal))
    , ((4, 6), MkWall (MkWallShape Horizontal))
    , ((5, 6), MkWall (MkWallShape Horizontal))
    , ((6, 6), MkWall (MkWallShape Horizontal))
    , ((7, 6), MkWall (MkWallShape Horizontal))
    , ((8, 6), MkWall (MkWallShape Horizontal))
    , ((9, 6), MkWall (MkWallShape Horizontal))
    , ((10, 6), MkWall (MkWallShape Horizontal))
    , ((11, 6), MkWall (MkCorner NW))
    ]
