module Model.CustomMaze where

import Model.Maze

import qualified Data.Map as Map

-- generated using:
-- python .\scripts\mazebuilder_v2.py .\scripts\data\maze_t_corners.txt -m Model.CustomMaze -o .\src\Model\CustomMaze.hs -i Model.Maze -v
customMaze :: Maze
customMaze = foldr f Map.empty xs
 where 
  f (k, v) = Map.insert k v
  xs = 
    [ ((0, 0), MkWall (MkCorner SE))
    , ((0, 1), MkWall (MkCorner SE))
    , ((0, 2), MkWall (MkCorner SE))
    , ((0, 3), MkWall (MkCorner SE))
    , ((0, 4), MkWall (MkCorner SE))
    , ((0, 5), MkWall (MkCorner SE))
    , ((0, 6), MkWall (MkCorner SE))
    , ((0, 7), MkWall (MkCorner SE))
    , ((0, 8), MkWall (MkCorner SE))
    , ((0, 9), MkWall (MkCorner SE))
    , ((0, 10), MkWall (MkCorner SE))
    , ((0, 11), MkWall (MkCorner SW))
    , ((1, 0), MkWall (MkWallShape Vertical))
    , ((1, 1), MkWall (MkCorner SE))
    , ((1, 2), MkWall (MkCorner SE))
    , ((1, 3), MkWall (MkCorner SE))
    , ((1, 4), MkWall (MkCorner SE))
    , ((1, 5), MkWall (MkCorner SW))
    , ((1, 6), MkWall (MkCorner SE))
    , ((1, 7), MkWall (MkCorner SE))
    , ((1, 8), MkWall (MkCorner SE))
    , ((1, 9), MkWall (MkCorner SE))
    , ((1, 10), MkWall (MkCorner SW))
    , ((1, 11), MkWall (MkWallShape Vertical))
    , ((2, 0), MkWall (MkWallShape Vertical))
    , ((2, 1), MkWall (MkWallShape Vertical))
    , ((2, 2), MkFloor EmptyTile)
    , ((2, 3), MkFloor EmptyTile)
    , ((2, 4), MkFloor EmptyTile)
    , ((2, 5), MkWall (MkWallShape Vertical))
    , ((2, 6), MkWall (MkWallShape Vertical))
    , ((2, 7), MkFloor EmptyTile)
    , ((2, 8), MkFloor EmptyTile)
    , ((2, 9), MkFloor EmptyTile)
    , ((2, 10), MkWall (MkWallShape Vertical))
    , ((2, 11), MkWall (MkWallShape Vertical))
    , ((3, 0), MkWall (MkWallShape Vertical))
    , ((3, 1), MkWall (MkWallShape Vertical))
    , ((3, 2), MkFloor EmptyTile)
    , ((3, 3), MkFloor EmptyTile)
    , ((3, 4), MkFloor EmptyTile)
    , ((3, 5), MkWall (MkCorner NE))
    , ((3, 6), MkWall (MkCorner NW))
    , ((3, 7), MkFloor EmptyTile)
    , ((3, 8), MkFloor EmptyTile)
    , ((3, 9), MkFloor EmptyTile)
    , ((3, 10), MkWall (MkWallShape Vertical))
    , ((3, 11), MkWall (MkWallShape Vertical))
    , ((4, 0), MkWall (MkWallShape Vertical))
    , ((4, 1), MkWall (MkCorner NE))
    , ((4, 2), MkWall (MkCorner NE))
    , ((4, 3), MkWall (MkCorner SW))
    , ((4, 4), MkFloor EmptyTile)
    , ((4, 5), MkFloor EmptyTile)
    , ((4, 6), MkFloor EmptyTile)
    , ((4, 7), MkFloor EmptyTile)
    , ((4, 8), MkWall (MkCorner SE))
    , ((4, 9), MkWall (MkCorner SE))
    , ((4, 10), MkWall (MkCorner NW))
    , ((4, 11), MkWall (MkWallShape Vertical))
    , ((5, 0), MkWall (MkWallShape Vertical))
    , ((5, 1), MkWall (MkCorner SE))
    , ((5, 2), MkWall (MkCorner SE))
    , ((5, 3), MkWall (MkCorner NW))
    , ((5, 4), MkFloor EmptyTile)
    , ((5, 5), MkFloor EmptyTile)
    , ((5, 6), MkFloor EmptyTile)
    , ((5, 7), MkFloor EmptyTile)
    , ((5, 8), MkWall (MkCorner NE))
    , ((5, 9), MkWall (MkCorner NE))
    , ((5, 10), MkWall (MkCorner SW))
    , ((5, 11), MkWall (MkWallShape Vertical))
    , ((6, 0), MkWall (MkWallShape Vertical))
    , ((6, 1), MkWall (MkWallShape Vertical))
    , ((6, 2), MkFloor EmptyTile)
    , ((6, 3), MkFloor EmptyTile)
    , ((6, 4), MkFloor EmptyTile)
    , ((6, 5), MkWall (MkCorner SE))
    , ((6, 6), MkWall (MkCorner SW))
    , ((6, 7), MkFloor EmptyTile)
    , ((6, 8), MkFloor EmptyTile)
    , ((6, 9), MkFloor EmptyTile)
    , ((6, 10), MkWall (MkWallShape Vertical))
    , ((6, 11), MkWall (MkWallShape Vertical))
    , ((7, 0), MkWall (MkWallShape Vertical))
    , ((7, 1), MkWall (MkWallShape Vertical))
    , ((7, 2), MkFloor EmptyTile)
    , ((7, 3), MkFloor EmptyTile)
    , ((7, 4), MkFloor EmptyTile)
    , ((7, 5), MkWall (MkWallShape Vertical))
    , ((7, 6), MkWall (MkWallShape Vertical))
    , ((7, 7), MkFloor EmptyTile)
    , ((7, 8), MkFloor EmptyTile)
    , ((7, 9), MkFloor EmptyTile)
    , ((7, 10), MkWall (MkWallShape Vertical))
    , ((7, 11), MkWall (MkWallShape Vertical))
    , ((8, 0), MkWall (MkWallShape Vertical))
    , ((8, 1), MkWall (MkCorner NE))
    , ((8, 2), MkWall (MkCorner NE))
    , ((8, 3), MkWall (MkCorner NE))
    , ((8, 4), MkWall (MkCorner NE))
    , ((8, 5), MkWall (MkCorner NW))
    , ((8, 6), MkWall (MkCorner NE))
    , ((8, 7), MkWall (MkCorner NE))
    , ((8, 8), MkWall (MkCorner NE))
    , ((8, 9), MkWall (MkCorner NE))
    , ((8, 10), MkWall (MkCorner NW))
    , ((8, 11), MkWall (MkWallShape Vertical))
    , ((9, 0), MkWall (MkCorner NE))
    , ((9, 1), MkWall (MkCorner NE))
    , ((9, 2), MkWall (MkCorner NE))
    , ((9, 3), MkWall (MkCorner NE))
    , ((9, 4), MkWall (MkCorner NE))
    , ((9, 5), MkWall (MkCorner NE))
    , ((9, 6), MkWall (MkCorner NE))
    , ((9, 7), MkWall (MkCorner NE))
    , ((9, 8), MkWall (MkCorner NE))
    , ((9, 9), MkWall (MkCorner NE))
    , ((9, 10), MkWall (MkCorner NE))
    , ((9, 11), MkWall (MkCorner NW))
    ]
