module Model.CustomMaze where

import Model.Maze

import qualified Data.Map as Map

-- generated using:
-- python .\scripts\mazebuilder_v2.py .\scripts\data\maze_large.txt -m Model.CustomMaze -o .\src\Model\CustomMaze.hs -i Model.Maze -v
customMaze :: Maze
customMaze = foldr f Map.empty xs
 where 
  f (k, v) = Map.insert k v
  xs = 
    [ ((0, 0), MkWall (MkCorner SE))
    , ((1, 0), MkWall (MkWallShape Horizontal))
    , ((2, 0), MkWall (MkWallShape Horizontal))
    , ((3, 0), MkWall (MkWallShape Horizontal))
    , ((4, 0), MkWall (MkWallShape Horizontal))
    , ((5, 0), MkWall (MkWallShape Horizontal))
    , ((6, 0), MkWall (MkWallShape Horizontal))
    , ((7, 0), MkWall (MkWallShape Horizontal))
    , ((8, 0), MkWall (MkWallShape Horizontal))
    , ((9, 0), MkWall (MkWallShape Horizontal))
    , ((10, 0), MkWall (MkWallShape Horizontal))
    , ((11, 0), MkWall (MkWallShape Horizontal))
    , ((12, 0), MkWall (MkWallShape Horizontal))
    , ((13, 0), MkWall (MkWallShape Horizontal))
    , ((14, 0), MkWall (MkWallShape Horizontal))
    , ((15, 0), MkWall (MkWallShape Horizontal))
    , ((16, 0), MkWall (MkWallShape Horizontal))
    , ((17, 0), MkWall (MkWallShape Horizontal))
    , ((18, 0), MkWall (MkWallShape Horizontal))
    , ((19, 0), MkWall (MkWallShape Horizontal))
    , ((20, 0), MkWall (MkWallShape Horizontal))
    , ((21, 0), MkWall (MkWallShape Horizontal))
    , ((22, 0), MkWall (MkWallShape Horizontal))
    , ((23, 0), MkWall (MkWallShape Horizontal))
    , ((24, 0), MkWall (MkWallShape Horizontal))
    , ((25, 0), MkWall (MkWallShape Horizontal))
    , ((26, 0), MkWall (MkWallShape Horizontal))
    , ((27, 0), MkWall (MkWallShape Horizontal))
    , ((28, 0), MkWall (MkWallShape Horizontal))
    , ((29, 0), MkWall (MkCorner SW))
    , ((0, 1), MkWall (MkWallShape Vertical))
    , ((1, 1), MkWall (MkCorner SE))
    , ((2, 1), MkWall (MkWallShape Horizontal))
    , ((3, 1), MkWall (MkWallShape Horizontal))
    , ((4, 1), MkWall (MkWallShape Horizontal))
    , ((5, 1), MkWall (MkWallShape Horizontal))
    , ((6, 1), MkWall (MkWallShape Horizontal))
    , ((7, 1), MkWall (MkWallShape Horizontal))
    , ((8, 1), MkWall (MkWallShape Horizontal))
    , ((9, 1), MkWall (MkWallShape Horizontal))
    , ((10, 1), MkWall (MkWallShape Horizontal))
    , ((11, 1), MkWall (MkWallShape Horizontal))
    , ((12, 1), MkWall (MkWallShape Horizontal))
    , ((13, 1), MkWall (MkWallShape Horizontal))
    , ((14, 1), MkWall (MkCorner SW))
    , ((15, 1), MkWall (MkCorner SE))
    , ((16, 1), MkWall (MkWallShape Horizontal))
    , ((17, 1), MkWall (MkWallShape Horizontal))
    , ((18, 1), MkWall (MkWallShape Horizontal))
    , ((19, 1), MkWall (MkWallShape Horizontal))
    , ((20, 1), MkWall (MkWallShape Horizontal))
    , ((21, 1), MkWall (MkWallShape Horizontal))
    , ((22, 1), MkWall (MkWallShape Horizontal))
    , ((23, 1), MkWall (MkWallShape Horizontal))
    , ((24, 1), MkWall (MkWallShape Horizontal))
    , ((25, 1), MkWall (MkWallShape Horizontal))
    , ((26, 1), MkWall (MkWallShape Horizontal))
    , ((27, 1), MkWall (MkWallShape Horizontal))
    , ((28, 1), MkWall (MkCorner SW))
    , ((29, 1), MkWall (MkWallShape Vertical))
    , ((0, 2), MkWall (MkWallShape Vertical))
    , ((1, 2), MkWall (MkWallShape Vertical))
    , ((2, 2), MkFloor EmptyTile)
    , ((3, 2), MkFloor EmptyTile)
    , ((4, 2), MkFloor EmptyTile)
    , ((5, 2), MkFloor EmptyTile)
    , ((6, 2), MkFloor EmptyTile)
    , ((7, 2), MkFloor EmptyTile)
    , ((8, 2), MkFloor EmptyTile)
    , ((9, 2), MkFloor EmptyTile)
    , ((10, 2), MkFloor EmptyTile)
    , ((11, 2), MkFloor EmptyTile)
    , ((12, 2), MkFloor EmptyTile)
    , ((13, 2), MkFloor EmptyTile)
    , ((14, 2), MkWall (MkWallShape Vertical))
    , ((15, 2), MkWall (MkWallShape Vertical))
    , ((16, 2), MkFloor EmptyTile)
    , ((17, 2), MkFloor EmptyTile)
    , ((18, 2), MkFloor EmptyTile)
    , ((19, 2), MkFloor EmptyTile)
    , ((20, 2), MkFloor EmptyTile)
    , ((21, 2), MkFloor EmptyTile)
    , ((22, 2), MkFloor EmptyTile)
    , ((23, 2), MkFloor EmptyTile)
    , ((24, 2), MkFloor EmptyTile)
    , ((25, 2), MkFloor EmptyTile)
    , ((26, 2), MkFloor EmptyTile)
    , ((27, 2), MkFloor EmptyTile)
    , ((28, 2), MkWall (MkWallShape Vertical))
    , ((29, 2), MkWall (MkWallShape Vertical))
    , ((0, 3), MkWall (MkWallShape Vertical))
    , ((1, 3), MkWall (MkWallShape Vertical))
    , ((2, 3), MkFloor EmptyTile)
    , ((3, 3), MkWall (MkCorner SE))
    , ((4, 3), MkWall (MkWallShape Horizontal))
    , ((5, 3), MkWall (MkWallShape Horizontal))
    , ((6, 3), MkWall (MkCorner SW))
    , ((7, 3), MkFloor EmptyTile)
    , ((8, 3), MkWall (MkCorner SE))
    , ((9, 3), MkWall (MkWallShape Horizontal))
    , ((10, 3), MkWall (MkWallShape Horizontal))
    , ((11, 3), MkWall (MkWallShape Horizontal))
    , ((12, 3), MkWall (MkCorner SW))
    , ((13, 3), MkFloor EmptyTile)
    , ((14, 3), MkWall (MkWallShape Vertical))
    , ((15, 3), MkWall (MkWallShape Vertical))
    , ((16, 3), MkFloor EmptyTile)
    , ((17, 3), MkWall (MkCorner SE))
    , ((18, 3), MkWall (MkWallShape Horizontal))
    , ((19, 3), MkWall (MkWallShape Horizontal))
    , ((20, 3), MkWall (MkWallShape Horizontal))
    , ((21, 3), MkWall (MkCorner SW))
    , ((22, 3), MkFloor EmptyTile)
    , ((23, 3), MkWall (MkCorner SE))
    , ((24, 3), MkWall (MkWallShape Horizontal))
    , ((25, 3), MkWall (MkWallShape Horizontal))
    , ((26, 3), MkWall (MkCorner SW))
    , ((27, 3), MkFloor EmptyTile)
    , ((28, 3), MkWall (MkWallShape Vertical))
    , ((29, 3), MkWall (MkWallShape Vertical))
    , ((0, 4), MkWall (MkWallShape Vertical))
    , ((1, 4), MkWall (MkWallShape Vertical))
    , ((2, 4), MkFloor EmptyTile)
    , ((3, 4), MkWall (MkWallShape Vertical))
    , ((4, 4), MkFloor EmptyTile)
    , ((5, 4), MkFloor EmptyTile)
    , ((6, 4), MkWall (MkWallShape Vertical))
    , ((7, 4), MkFloor EmptyTile)
    , ((8, 4), MkWall (MkWallShape Vertical))
    , ((9, 4), MkFloor EmptyTile)
    , ((10, 4), MkFloor EmptyTile)
    , ((11, 4), MkFloor EmptyTile)
    , ((12, 4), MkWall (MkWallShape Vertical))
    , ((13, 4), MkFloor EmptyTile)
    , ((14, 4), MkWall (MkWallShape Vertical))
    , ((15, 4), MkWall (MkWallShape Vertical))
    , ((16, 4), MkFloor EmptyTile)
    , ((17, 4), MkWall (MkWallShape Vertical))
    , ((18, 4), MkFloor EmptyTile)
    , ((19, 4), MkFloor EmptyTile)
    , ((20, 4), MkFloor EmptyTile)
    , ((21, 4), MkWall (MkWallShape Vertical))
    , ((22, 4), MkFloor EmptyTile)
    , ((23, 4), MkWall (MkWallShape Vertical))
    , ((24, 4), MkFloor EmptyTile)
    , ((25, 4), MkFloor EmptyTile)
    , ((26, 4), MkWall (MkWallShape Vertical))
    , ((27, 4), MkFloor EmptyTile)
    , ((28, 4), MkWall (MkWallShape Vertical))
    , ((29, 4), MkWall (MkWallShape Vertical))
    , ((0, 5), MkWall (MkWallShape Vertical))
    , ((1, 5), MkWall (MkWallShape Vertical))
    , ((2, 5), MkFloor EmptyTile)
    , ((3, 5), MkWall (MkCorner NE))
    , ((4, 5), MkWall (MkWallShape Horizontal))
    , ((5, 5), MkWall (MkWallShape Horizontal))
    , ((6, 5), MkWall (MkCorner NW))
    , ((7, 5), MkFloor EmptyTile)
    , ((8, 5), MkWall (MkCorner NE))
    , ((9, 5), MkWall (MkWallShape Horizontal))
    , ((10, 5), MkWall (MkWallShape Horizontal))
    , ((11, 5), MkWall (MkWallShape Horizontal))
    , ((12, 5), MkWall (MkCorner NW))
    , ((13, 5), MkFloor EmptyTile)
    , ((14, 5), MkWall (MkCorner NE))
    , ((15, 5), MkWall (MkCorner NW))
    , ((16, 5), MkFloor EmptyTile)
    , ((17, 5), MkWall (MkCorner NE))
    , ((18, 5), MkWall (MkWallShape Horizontal))
    , ((19, 5), MkWall (MkWallShape Horizontal))
    , ((20, 5), MkWall (MkWallShape Horizontal))
    , ((21, 5), MkWall (MkCorner NW))
    , ((22, 5), MkFloor EmptyTile)
    , ((23, 5), MkWall (MkCorner NE))
    , ((24, 5), MkWall (MkWallShape Horizontal))
    , ((25, 5), MkWall (MkWallShape Horizontal))
    , ((26, 5), MkWall (MkCorner NW))
    , ((27, 5), MkFloor EmptyTile)
    , ((28, 5), MkWall (MkWallShape Vertical))
    , ((29, 5), MkWall (MkWallShape Vertical))
    , ((0, 6), MkWall (MkWallShape Vertical))
    , ((1, 6), MkWall (MkWallShape Vertical))
    , ((2, 6), MkFloor EmptyTile)
    , ((3, 6), MkFloor EmptyTile)
    , ((4, 6), MkFloor EmptyTile)
    , ((5, 6), MkFloor EmptyTile)
    , ((6, 6), MkFloor EmptyTile)
    , ((7, 6), MkFloor EmptyTile)
    , ((8, 6), MkFloor EmptyTile)
    , ((9, 6), MkFloor EmptyTile)
    , ((10, 6), MkFloor EmptyTile)
    , ((11, 6), MkFloor EmptyTile)
    , ((12, 6), MkFloor EmptyTile)
    , ((13, 6), MkFloor EmptyTile)
    , ((14, 6), MkFloor EmptyTile)
    , ((15, 6), MkFloor EmptyTile)
    , ((16, 6), MkFloor (MkConsumable SuperPellet))
    , ((17, 6), MkFloor EmptyTile)
    , ((18, 6), MkFloor EmptyTile)
    , ((19, 6), MkFloor EmptyTile)
    , ((20, 6), MkFloor EmptyTile)
    , ((21, 6), MkFloor EmptyTile)
    , ((22, 6), MkFloor EmptyTile)
    , ((23, 6), MkFloor EmptyTile)
    , ((24, 6), MkFloor EmptyTile)
    , ((25, 6), MkFloor EmptyTile)
    , ((26, 6), MkFloor EmptyTile)
    , ((27, 6), MkFloor EmptyTile)
    , ((28, 6), MkWall (MkWallShape Vertical))
    , ((29, 6), MkWall (MkWallShape Vertical))
    , ((0, 7), MkWall (MkWallShape Vertical))
    , ((1, 7), MkWall (MkWallShape Vertical))
    , ((2, 7), MkFloor EmptyTile)
    , ((3, 7), MkWall (MkCorner SE))
    , ((4, 7), MkWall (MkWallShape Horizontal))
    , ((5, 7), MkWall (MkWallShape Horizontal))
    , ((6, 7), MkWall (MkCorner SW))
    , ((7, 7), MkFloor EmptyTile)
    , ((8, 7), MkWall (MkCorner SE))
    , ((9, 7), MkWall (MkCorner SW))
    , ((10, 7), MkFloor EmptyTile)
    , ((11, 7), MkWall (MkCorner SE))
    , ((12, 7), MkWall (MkWallShape Horizontal))
    , ((13, 7), MkWall (MkWallShape Horizontal))
    , ((14, 7), MkWall (MkWallShape Horizontal))
    , ((15, 7), MkWall (MkWallShape Horizontal))
    , ((16, 7), MkWall (MkWallShape Horizontal))
    , ((17, 7), MkWall (MkCorner SW))
    , ((18, 7), MkFloor EmptyTile)
    , ((19, 7), MkFloor EmptyTile)
    , ((20, 7), MkWall (MkCorner SE))
    , ((21, 7), MkWall (MkCorner SW))
    , ((22, 7), MkFloor EmptyTile)
    , ((23, 7), MkWall (MkCorner SE))
    , ((24, 7), MkWall (MkWallShape Horizontal))
    , ((25, 7), MkWall (MkWallShape Horizontal))
    , ((26, 7), MkWall (MkCorner SW))
    , ((27, 7), MkFloor EmptyTile)
    , ((28, 7), MkWall (MkWallShape Vertical))
    , ((29, 7), MkWall (MkWallShape Vertical))
    , ((0, 8), MkWall (MkWallShape Vertical))
    , ((1, 8), MkWall (MkWallShape Vertical))
    , ((2, 8), MkFloor EmptyTile)
    , ((3, 8), MkWall (MkCorner NE))
    , ((4, 8), MkWall (MkWallShape Horizontal))
    , ((5, 8), MkWall (MkWallShape Horizontal))
    , ((6, 8), MkWall (MkCorner NW))
    , ((7, 8), MkFloor EmptyTile)
    , ((8, 8), MkWall (MkWallShape Vertical))
    , ((9, 8), MkWall (MkWallShape Vertical))
    , ((10, 8), MkFloor EmptyTile)
    , ((11, 8), MkWall (MkCorner NE))
    , ((12, 8), MkWall (MkWallShape Horizontal))
    , ((13, 8), MkWall (MkWallShape Horizontal))
    , ((14, 8), MkWall (MkCorner SW))
    , ((15, 8), MkWall (MkCorner SE))
    , ((16, 8), MkWall (MkWallShape Horizontal))
    , ((17, 8), MkWall (MkCorner NW))
    , ((18, 8), MkFloor EmptyTile)
    , ((19, 8), MkFloor EmptyTile)
    , ((20, 8), MkWall (MkWallShape Vertical))
    , ((21, 8), MkWall (MkWallShape Vertical))
    , ((22, 8), MkFloor EmptyTile)
    , ((23, 8), MkWall (MkCorner NE))
    , ((24, 8), MkWall (MkWallShape Horizontal))
    , ((25, 8), MkWall (MkWallShape Horizontal))
    , ((26, 8), MkWall (MkCorner NW))
    , ((27, 8), MkFloor EmptyTile)
    , ((28, 8), MkWall (MkWallShape Vertical))
    , ((29, 8), MkWall (MkWallShape Vertical))
    , ((0, 9), MkWall (MkWallShape Vertical))
    , ((1, 9), MkWall (MkWallShape Vertical))
    , ((2, 9), MkFloor EmptyTile)
    , ((3, 9), MkFloor EmptyTile)
    , ((4, 9), MkFloor EmptyTile)
    , ((5, 9), MkFloor EmptyTile)
    , ((6, 9), MkFloor EmptyTile)
    , ((7, 9), MkFloor EmptyTile)
    , ((8, 9), MkWall (MkWallShape Vertical))
    , ((9, 9), MkWall (MkWallShape Vertical))
    , ((10, 9), MkFloor EmptyTile)
    , ((11, 9), MkFloor EmptyTile)
    , ((12, 9), MkFloor EmptyTile)
    , ((13, 9), MkFloor EmptyTile)
    , ((14, 9), MkWall (MkWallShape Vertical))
    , ((15, 9), MkWall (MkWallShape Vertical))
    , ((16, 9), MkFloor EmptyTile)
    , ((17, 9), MkFloor EmptyTile)
    , ((18, 9), MkFloor EmptyTile)
    , ((19, 9), MkFloor EmptyTile)
    , ((20, 9), MkWall (MkWallShape Vertical))
    , ((21, 9), MkWall (MkWallShape Vertical))
    , ((22, 9), MkFloor EmptyTile)
    , ((23, 9), MkFloor EmptyTile)
    , ((24, 9), MkFloor EmptyTile)
    , ((25, 9), MkFloor EmptyTile)
    , ((26, 9), MkFloor EmptyTile)
    , ((27, 9), MkFloor EmptyTile)
    , ((28, 9), MkWall (MkWallShape Vertical))
    , ((29, 9), MkWall (MkWallShape Vertical))
    , ((0, 10), MkWall (MkWallShape Vertical))
    , ((1, 10), MkWall (MkCorner NE))
    , ((2, 10), MkWall (MkWallShape Horizontal))
    , ((3, 10), MkWall (MkWallShape Horizontal))
    , ((4, 10), MkWall (MkWallShape Horizontal))
    , ((5, 10), MkWall (MkWallShape Horizontal))
    , ((6, 10), MkWall (MkCorner SW))
    , ((7, 10), MkFloor EmptyTile)
    , ((8, 10), MkWall (MkWallShape Vertical))
    , ((9, 10), MkWall (MkCorner NE))
    , ((10, 10), MkWall (MkWallShape Horizontal))
    , ((11, 10), MkWall (MkWallShape Horizontal))
    , ((12, 10), MkWall (MkCorner SW))
    , ((13, 10), MkFloor EmptyTile)
    , ((14, 10), MkWall (MkWallShape Vertical))
    , ((15, 10), MkWall (MkWallShape Vertical))
    , ((16, 10), MkFloor EmptyTile)
    , ((17, 10), MkWall (MkCorner SE))
    , ((18, 10), MkWall (MkWallShape Horizontal))
    , ((19, 10), MkWall (MkWallShape Horizontal))
    , ((20, 10), MkWall (MkCorner NW))
    , ((21, 10), MkWall (MkWallShape Vertical))
    , ((22, 10), MkFloor EmptyTile)
    , ((23, 10), MkWall (MkCorner SE))
    , ((24, 10), MkWall (MkWallShape Horizontal))
    , ((25, 10), MkWall (MkWallShape Horizontal))
    , ((26, 10), MkWall (MkWallShape Horizontal))
    , ((27, 10), MkWall (MkWallShape Horizontal))
    , ((28, 10), MkWall (MkCorner NW))
    , ((29, 10), MkWall (MkWallShape Vertical))
    , ((0, 11), MkWall (MkWallShape Vertical))
    , ((1, 11), MkFloor EmptyTile)
    , ((2, 11), MkFloor EmptyTile)
    , ((3, 11), MkFloor EmptyTile)
    , ((4, 11), MkFloor EmptyTile)
    , ((5, 11), MkFloor EmptyTile)
    , ((6, 11), MkWall (MkWallShape Vertical))
    , ((7, 11), MkFloor EmptyTile)
    , ((8, 11), MkWall (MkWallShape Vertical))
    , ((9, 11), MkWall (MkCorner SE))
    , ((10, 11), MkWall (MkWallShape Horizontal))
    , ((11, 11), MkWall (MkWallShape Horizontal))
    , ((12, 11), MkWall (MkCorner NW))
    , ((13, 11), MkFloor EmptyTile)
    , ((14, 11), MkWall (MkCorner NE))
    , ((15, 11), MkWall (MkCorner NW))
    , ((16, 11), MkFloor EmptyTile)
    , ((17, 11), MkWall (MkCorner NE))
    , ((18, 11), MkWall (MkWallShape Horizontal))
    , ((19, 11), MkWall (MkWallShape Horizontal))
    , ((20, 11), MkWall (MkCorner SW))
    , ((21, 11), MkWall (MkWallShape Vertical))
    , ((22, 11), MkFloor EmptyTile)
    , ((23, 11), MkWall (MkWallShape Vertical))
    , ((24, 11), MkFloor EmptyTile)
    , ((25, 11), MkFloor EmptyTile)
    , ((26, 11), MkFloor EmptyTile)
    , ((27, 11), MkFloor EmptyTile)
    , ((28, 11), MkFloor EmptyTile)
    , ((29, 11), MkWall (MkWallShape Vertical))
    , ((0, 12), MkWall (MkWallShape Vertical))
    , ((1, 12), MkFloor EmptyTile)
    , ((2, 12), MkFloor EmptyTile)
    , ((3, 12), MkFloor EmptyTile)
    , ((4, 12), MkFloor EmptyTile)
    , ((5, 12), MkFloor EmptyTile)
    , ((6, 12), MkWall (MkWallShape Vertical))
    , ((7, 12), MkFloor EmptyTile)
    , ((8, 12), MkWall (MkWallShape Vertical))
    , ((9, 12), MkWall (MkWallShape Vertical))
    , ((10, 12), MkFloor EmptyTile)
    , ((11, 12), MkFloor EmptyTile)
    , ((12, 12), MkFloor EmptyTile)
    , ((13, 12), MkFloor EmptyTile)
    , ((14, 12), MkFloor EmptyTile)
    , ((15, 12), MkFloor EmptyTile)
    , ((16, 12), MkFloor EmptyTile)
    , ((17, 12), MkFloor EmptyTile)
    , ((18, 12), MkFloor (MkConsumable Pellet))
    , ((19, 12), MkFloor EmptyTile)
    , ((20, 12), MkWall (MkWallShape Vertical))
    , ((21, 12), MkWall (MkWallShape Vertical))
    , ((22, 12), MkFloor EmptyTile)
    , ((23, 12), MkWall (MkWallShape Vertical))
    , ((24, 12), MkFloor EmptyTile)
    , ((25, 12), MkFloor EmptyTile)
    , ((26, 12), MkFloor EmptyTile)
    , ((27, 12), MkFloor EmptyTile)
    , ((28, 12), MkFloor EmptyTile)
    , ((29, 12), MkWall (MkWallShape Vertical))
    , ((0, 13), MkWall (MkWallShape Vertical))
    , ((1, 13), MkFloor EmptyTile)
    , ((2, 13), MkFloor EmptyTile)
    , ((3, 13), MkFloor EmptyTile)
    , ((4, 13), MkFloor EmptyTile)
    , ((5, 13), MkFloor EmptyTile)
    , ((6, 13), MkWall (MkWallShape Vertical))
    , ((7, 13), MkFloor EmptyTile)
    , ((8, 13), MkWall (MkWallShape Vertical))
    , ((9, 13), MkWall (MkWallShape Vertical))
    , ((10, 13), MkFloor EmptyTile)
    , ((11, 13), MkFloor EmptyTile)
    , ((12, 13), MkFloor EmptyTile)
    , ((13, 13), MkWall (MkCorner SE))
    , ((14, 13), MkWall (MkWallShape Horizontal))
    , ((15, 13), MkWall (MkWallShape Horizontal))
    , ((16, 13), MkWall (MkCorner SW))
    , ((17, 13), MkFloor EmptyTile)
    , ((18, 13), MkFloor EmptyTile)
    , ((19, 13), MkFloor EmptyTile)
    , ((20, 13), MkWall (MkWallShape Vertical))
    , ((21, 13), MkWall (MkWallShape Vertical))
    , ((22, 13), MkFloor EmptyTile)
    , ((23, 13), MkWall (MkWallShape Vertical))
    , ((24, 13), MkFloor EmptyTile)
    , ((25, 13), MkFloor EmptyTile)
    , ((26, 13), MkFloor EmptyTile)
    , ((27, 13), MkFloor EmptyTile)
    , ((28, 13), MkFloor EmptyTile)
    , ((29, 13), MkWall (MkWallShape Vertical))
    , ((0, 14), MkWall (MkWallShape Vertical))
    , ((1, 14), MkWall (MkCorner SE))
    , ((2, 14), MkWall (MkWallShape Horizontal))
    , ((3, 14), MkWall (MkWallShape Horizontal))
    , ((4, 14), MkWall (MkWallShape Horizontal))
    , ((5, 14), MkWall (MkWallShape Horizontal))
    , ((6, 14), MkWall (MkCorner NW))
    , ((7, 14), MkFloor EmptyTile)
    , ((8, 14), MkWall (MkCorner NE))
    , ((9, 14), MkWall (MkCorner NW))
    , ((10, 14), MkFloor EmptyTile)
    , ((11, 14), MkFloor EmptyTile)
    , ((12, 14), MkFloor EmptyTile)
    , ((13, 14), MkWall (MkWallShape Vertical))
    , ((14, 14), MkFloor EmptyTile)
    , ((15, 14), MkFloor EmptyTile)
    , ((16, 14), MkWall (MkWallShape Vertical))
    , ((17, 14), MkFloor EmptyTile)
    , ((18, 14), MkFloor EmptyTile)
    , ((19, 14), MkFloor EmptyTile)
    , ((20, 14), MkWall (MkCorner NE))
    , ((21, 14), MkWall (MkCorner NW))
    , ((22, 14), MkFloor EmptyTile)
    , ((23, 14), MkWall (MkCorner NE))
    , ((24, 14), MkWall (MkWallShape Horizontal))
    , ((25, 14), MkWall (MkWallShape Horizontal))
    , ((26, 14), MkWall (MkWallShape Horizontal))
    , ((27, 14), MkWall (MkWallShape Horizontal))
    , ((28, 14), MkWall (MkCorner SW))
    , ((29, 14), MkWall (MkWallShape Vertical))
    , ((0, 15), MkWall (MkWallShape Vertical))
    , ((1, 15), MkWall (MkWallShape Vertical))
    , ((2, 15), MkFloor EmptyTile)
    , ((3, 15), MkFloor EmptyTile)
    , ((4, 15), MkFloor EmptyTile)
    , ((5, 15), MkFloor EmptyTile)
    , ((6, 15), MkFloor EmptyTile)
    , ((7, 15), MkFloor EmptyTile)
    , ((8, 15), MkFloor EmptyTile)
    , ((9, 15), MkFloor EmptyTile)
    , ((10, 15), MkFloor EmptyTile)
    , ((11, 15), MkFloor EmptyTile)
    , ((12, 15), MkFloor EmptyTile)
    , ((13, 15), MkWall (MkWallShape Vertical))
    , ((14, 15), MkFloor EmptyTile)
    , ((15, 15), MkFloor EmptyTile)
    , ((16, 15), MkWall (MkWallShape Vertical))
    , ((17, 15), MkFloor EmptyTile)
    , ((18, 15), MkFloor EmptyTile)
    , ((19, 15), MkFloor EmptyTile)
    , ((20, 15), MkFloor EmptyTile)
    , ((21, 15), MkFloor EmptyTile)
    , ((22, 15), MkFloor EmptyTile)
    , ((23, 15), MkFloor EmptyTile)
    , ((24, 15), MkFloor EmptyTile)
    , ((25, 15), MkFloor EmptyTile)
    , ((26, 15), MkFloor EmptyTile)
    , ((27, 15), MkFloor EmptyTile)
    , ((28, 15), MkWall (MkWallShape Vertical))
    , ((29, 15), MkWall (MkWallShape Vertical))
    , ((0, 16), MkWall (MkWallShape Vertical))
    , ((1, 16), MkWall (MkCorner NE))
    , ((2, 16), MkWall (MkWallShape Horizontal))
    , ((3, 16), MkWall (MkWallShape Horizontal))
    , ((4, 16), MkWall (MkWallShape Horizontal))
    , ((5, 16), MkWall (MkWallShape Horizontal))
    , ((6, 16), MkWall (MkCorner SW))
    , ((7, 16), MkFloor EmptyTile)
    , ((8, 16), MkWall (MkCorner SE))
    , ((9, 16), MkWall (MkCorner SW))
    , ((10, 16), MkFloor EmptyTile)
    , ((11, 16), MkWall (MkCorner SE))
    , ((12, 16), MkWall (MkWallShape Horizontal))
    , ((13, 16), MkWall (MkCorner NW))
    , ((14, 16), MkFloor EmptyTile)
    , ((15, 16), MkFloor EmptyTile)
    , ((16, 16), MkWall (MkCorner NE))
    , ((17, 16), MkWall (MkWallShape Horizontal))
    , ((18, 16), MkWall (MkCorner SW))
    , ((19, 16), MkFloor EmptyTile)
    , ((20, 16), MkWall (MkCorner SE))
    , ((21, 16), MkWall (MkCorner SW))
    , ((22, 16), MkFloor EmptyTile)
    , ((23, 16), MkWall (MkCorner SE))
    , ((24, 16), MkWall (MkWallShape Horizontal))
    , ((25, 16), MkWall (MkWallShape Horizontal))
    , ((26, 16), MkWall (MkWallShape Horizontal))
    , ((27, 16), MkWall (MkWallShape Horizontal))
    , ((28, 16), MkWall (MkCorner NW))
    , ((29, 16), MkWall (MkWallShape Vertical))
    , ((0, 17), MkWall (MkWallShape Vertical))
    , ((1, 17), MkFloor EmptyTile)
    , ((2, 17), MkFloor EmptyTile)
    , ((3, 17), MkFloor EmptyTile)
    , ((4, 17), MkFloor EmptyTile)
    , ((5, 17), MkFloor EmptyTile)
    , ((6, 17), MkWall (MkWallShape Vertical))
    , ((7, 17), MkFloor EmptyTile)
    , ((8, 17), MkWall (MkWallShape Vertical))
    , ((9, 17), MkWall (MkWallShape Vertical))
    , ((10, 17), MkFloor EmptyTile)
    , ((11, 17), MkWall (MkCorner NE))
    , ((12, 17), MkWall (MkWallShape Horizontal))
    , ((13, 17), MkWall (MkWallShape Horizontal))
    , ((14, 17), MkWall (MkWallShape Horizontal))
    , ((15, 17), MkWall (MkWallShape Horizontal))
    , ((16, 17), MkWall (MkWallShape Horizontal))
    , ((17, 17), MkWall (MkWallShape Horizontal))
    , ((18, 17), MkWall (MkCorner NW))
    , ((19, 17), MkFloor EmptyTile)
    , ((20, 17), MkWall (MkWallShape Vertical))
    , ((21, 17), MkWall (MkWallShape Vertical))
    , ((22, 17), MkFloor EmptyTile)
    , ((23, 17), MkWall (MkWallShape Vertical))
    , ((24, 17), MkFloor EmptyTile)
    , ((25, 17), MkFloor EmptyTile)
    , ((26, 17), MkFloor EmptyTile)
    , ((27, 17), MkFloor EmptyTile)
    , ((28, 17), MkFloor EmptyTile)
    , ((29, 17), MkWall (MkWallShape Vertical))
    , ((0, 18), MkWall (MkWallShape Vertical))
    , ((1, 18), MkFloor EmptyTile)
    , ((2, 18), MkFloor EmptyTile)
    , ((3, 18), MkFloor EmptyTile)
    , ((4, 18), MkFloor EmptyTile)
    , ((5, 18), MkFloor EmptyTile)
    , ((6, 18), MkWall (MkWallShape Vertical))
    , ((7, 18), MkFloor EmptyTile)
    , ((8, 18), MkWall (MkWallShape Vertical))
    , ((9, 18), MkWall (MkWallShape Vertical))
    , ((10, 18), MkFloor EmptyTile)
    , ((11, 18), MkFloor EmptyTile)
    , ((12, 18), MkFloor EmptyTile)
    , ((13, 18), MkFloor EmptyTile)
    , ((14, 18), MkFloor EmptyTile)
    , ((15, 18), MkFloor EmptyTile)
    , ((16, 18), MkFloor EmptyTile)
    , ((17, 18), MkFloor EmptyTile)
    , ((18, 18), MkFloor EmptyTile)
    , ((19, 18), MkFloor EmptyTile)
    , ((20, 18), MkWall (MkWallShape Vertical))
    , ((21, 18), MkWall (MkWallShape Vertical))
    , ((22, 18), MkFloor EmptyTile)
    , ((23, 18), MkWall (MkWallShape Vertical))
    , ((24, 18), MkFloor EmptyTile)
    , ((25, 18), MkFloor EmptyTile)
    , ((26, 18), MkFloor EmptyTile)
    , ((27, 18), MkFloor EmptyTile)
    , ((28, 18), MkFloor EmptyTile)
    , ((29, 18), MkWall (MkWallShape Vertical))
    , ((0, 19), MkWall (MkWallShape Vertical))
    , ((1, 19), MkFloor EmptyTile)
    , ((2, 19), MkFloor EmptyTile)
    , ((3, 19), MkFloor EmptyTile)
    , ((4, 19), MkFloor EmptyTile)
    , ((5, 19), MkFloor EmptyTile)
    , ((6, 19), MkWall (MkWallShape Vertical))
    , ((7, 19), MkFloor EmptyTile)
    , ((8, 19), MkWall (MkWallShape Vertical))
    , ((9, 19), MkWall (MkWallShape Vertical))
    , ((10, 19), MkFloor EmptyTile)
    , ((11, 19), MkWall (MkCorner SE))
    , ((12, 19), MkWall (MkWallShape Horizontal))
    , ((13, 19), MkWall (MkWallShape Horizontal))
    , ((14, 19), MkWall (MkWallShape Horizontal))
    , ((15, 19), MkWall (MkWallShape Horizontal))
    , ((16, 19), MkWall (MkWallShape Horizontal))
    , ((17, 19), MkWall (MkWallShape Horizontal))
    , ((18, 19), MkWall (MkCorner SW))
    , ((19, 19), MkFloor EmptyTile)
    , ((20, 19), MkWall (MkWallShape Vertical))
    , ((21, 19), MkWall (MkWallShape Vertical))
    , ((22, 19), MkFloor EmptyTile)
    , ((23, 19), MkWall (MkWallShape Vertical))
    , ((24, 19), MkFloor EmptyTile)
    , ((25, 19), MkFloor EmptyTile)
    , ((26, 19), MkFloor EmptyTile)
    , ((27, 19), MkFloor EmptyTile)
    , ((28, 19), MkFloor EmptyTile)
    , ((29, 19), MkWall (MkWallShape Vertical))
    , ((0, 20), MkWall (MkWallShape Vertical))
    , ((1, 20), MkWall (MkCorner SE))
    , ((2, 20), MkWall (MkWallShape Horizontal))
    , ((3, 20), MkWall (MkWallShape Horizontal))
    , ((4, 20), MkWall (MkWallShape Horizontal))
    , ((5, 20), MkWall (MkWallShape Horizontal))
    , ((6, 20), MkWall (MkCorner NW))
    , ((7, 20), MkFloor EmptyTile)
    , ((8, 20), MkWall (MkCorner NE))
    , ((9, 20), MkWall (MkCorner NW))
    , ((10, 20), MkFloor EmptyTile)
    , ((11, 20), MkWall (MkCorner NE))
    , ((12, 20), MkWall (MkWallShape Horizontal))
    , ((13, 20), MkWall (MkWallShape Horizontal))
    , ((14, 20), MkWall (MkCorner SW))
    , ((15, 20), MkWall (MkCorner SE))
    , ((16, 20), MkWall (MkWallShape Horizontal))
    , ((17, 20), MkWall (MkWallShape Horizontal))
    , ((18, 20), MkWall (MkCorner NW))
    , ((19, 20), MkFloor EmptyTile)
    , ((20, 20), MkWall (MkCorner NE))
    , ((21, 20), MkWall (MkCorner NW))
    , ((22, 20), MkFloor EmptyTile)
    , ((23, 20), MkWall (MkCorner NE))
    , ((24, 20), MkWall (MkWallShape Horizontal))
    , ((25, 20), MkWall (MkWallShape Horizontal))
    , ((26, 20), MkWall (MkWallShape Horizontal))
    , ((27, 20), MkWall (MkWallShape Horizontal))
    , ((28, 20), MkWall (MkCorner SW))
    , ((29, 20), MkWall (MkWallShape Vertical))
    , ((0, 21), MkWall (MkWallShape Vertical))
    , ((1, 21), MkWall (MkWallShape Vertical))
    , ((2, 21), MkFloor EmptyTile)
    , ((3, 21), MkFloor EmptyTile)
    , ((4, 21), MkFloor EmptyTile)
    , ((5, 21), MkFloor EmptyTile)
    , ((6, 21), MkFloor EmptyTile)
    , ((7, 21), MkFloor EmptyTile)
    , ((8, 21), MkFloor EmptyTile)
    , ((9, 21), MkFloor EmptyTile)
    , ((10, 21), MkFloor EmptyTile)
    , ((11, 21), MkFloor EmptyTile)
    , ((12, 21), MkFloor EmptyTile)
    , ((13, 21), MkFloor EmptyTile)
    , ((14, 21), MkWall (MkWallShape Vertical))
    , ((15, 21), MkWall (MkWallShape Vertical))
    , ((16, 21), MkFloor EmptyTile)
    , ((17, 21), MkFloor EmptyTile)
    , ((18, 21), MkFloor EmptyTile)
    , ((19, 21), MkFloor EmptyTile)
    , ((20, 21), MkFloor EmptyTile)
    , ((21, 21), MkFloor EmptyTile)
    , ((22, 21), MkFloor EmptyTile)
    , ((23, 21), MkFloor EmptyTile)
    , ((24, 21), MkFloor EmptyTile)
    , ((25, 21), MkFloor EmptyTile)
    , ((26, 21), MkFloor EmptyTile)
    , ((27, 21), MkFloor EmptyTile)
    , ((28, 21), MkWall (MkWallShape Vertical))
    , ((29, 21), MkWall (MkWallShape Vertical))
    , ((0, 22), MkWall (MkWallShape Vertical))
    , ((1, 22), MkWall (MkWallShape Vertical))
    , ((2, 22), MkFloor EmptyTile)
    , ((3, 22), MkWall (MkCorner SE))
    , ((4, 22), MkWall (MkWallShape Horizontal))
    , ((5, 22), MkWall (MkWallShape Horizontal))
    , ((6, 22), MkWall (MkCorner SW))
    , ((7, 22), MkFloor EmptyTile)
    , ((8, 22), MkWall (MkCorner SE))
    , ((9, 22), MkWall (MkWallShape Horizontal))
    , ((10, 22), MkWall (MkWallShape Horizontal))
    , ((11, 22), MkWall (MkWallShape Horizontal))
    , ((12, 22), MkWall (MkCorner SW))
    , ((13, 22), MkFloor EmptyTile)
    , ((14, 22), MkWall (MkWallShape Vertical))
    , ((15, 22), MkWall (MkWallShape Vertical))
    , ((16, 22), MkFloor EmptyTile)
    , ((17, 22), MkWall (MkCorner SE))
    , ((18, 22), MkWall (MkWallShape Horizontal))
    , ((19, 22), MkWall (MkWallShape Horizontal))
    , ((20, 22), MkWall (MkWallShape Horizontal))
    , ((21, 22), MkWall (MkCorner SW))
    , ((22, 22), MkFloor EmptyTile)
    , ((23, 22), MkWall (MkCorner SE))
    , ((24, 22), MkWall (MkWallShape Horizontal))
    , ((25, 22), MkWall (MkWallShape Horizontal))
    , ((26, 22), MkWall (MkCorner SW))
    , ((27, 22), MkFloor EmptyTile)
    , ((28, 22), MkWall (MkWallShape Vertical))
    , ((29, 22), MkWall (MkWallShape Vertical))
    , ((0, 23), MkWall (MkWallShape Vertical))
    , ((1, 23), MkWall (MkWallShape Vertical))
    , ((2, 23), MkFloor EmptyTile)
    , ((3, 23), MkWall (MkCorner NE))
    , ((4, 23), MkWall (MkWallShape Horizontal))
    , ((5, 23), MkWall (MkCorner SW))
    , ((6, 23), MkWall (MkWallShape Vertical))
    , ((7, 23), MkFloor EmptyTile)
    , ((8, 23), MkWall (MkCorner NE))
    , ((9, 23), MkWall (MkWallShape Horizontal))
    , ((10, 23), MkWall (MkWallShape Horizontal))
    , ((11, 23), MkWall (MkWallShape Horizontal))
    , ((12, 23), MkWall (MkCorner NW))
    , ((13, 23), MkFloor EmptyTile)
    , ((14, 23), MkWall (MkCorner NE))
    , ((15, 23), MkWall (MkCorner NW))
    , ((16, 23), MkFloor EmptyTile)
    , ((17, 23), MkWall (MkCorner NE))
    , ((18, 23), MkWall (MkWallShape Horizontal))
    , ((19, 23), MkWall (MkWallShape Horizontal))
    , ((20, 23), MkWall (MkWallShape Horizontal))
    , ((21, 23), MkWall (MkCorner NW))
    , ((22, 23), MkFloor EmptyTile)
    , ((23, 23), MkWall (MkWallShape Vertical))
    , ((24, 23), MkWall (MkCorner SE))
    , ((25, 23), MkWall (MkWallShape Horizontal))
    , ((26, 23), MkWall (MkCorner NW))
    , ((27, 23), MkFloor EmptyTile)
    , ((28, 23), MkWall (MkWallShape Vertical))
    , ((29, 23), MkWall (MkWallShape Vertical))
    , ((0, 24), MkWall (MkWallShape Vertical))
    , ((1, 24), MkWall (MkWallShape Vertical))
    , ((2, 24), MkFloor EmptyTile)
    , ((3, 24), MkFloor EmptyTile)
    , ((4, 24), MkFloor EmptyTile)
    , ((5, 24), MkWall (MkWallShape Vertical))
    , ((6, 24), MkWall (MkWallShape Vertical))
    , ((7, 24), MkFloor EmptyTile)
    , ((8, 24), MkFloor EmptyTile)
    , ((9, 24), MkFloor EmptyTile)
    , ((10, 24), MkFloor EmptyTile)
    , ((11, 24), MkFloor EmptyTile)
    , ((12, 24), MkFloor EmptyTile)
    , ((13, 24), MkFloor EmptyTile)
    , ((14, 24), MkFloor EmptyTile)
    , ((15, 24), MkFloor EmptyTile)
    , ((16, 24), MkFloor EmptyTile)
    , ((17, 24), MkFloor EmptyTile)
    , ((18, 24), MkFloor EmptyTile)
    , ((19, 24), MkFloor EmptyTile)
    , ((20, 24), MkFloor EmptyTile)
    , ((21, 24), MkFloor EmptyTile)
    , ((22, 24), MkFloor EmptyTile)
    , ((23, 24), MkWall (MkWallShape Vertical))
    , ((24, 24), MkWall (MkWallShape Vertical))
    , ((25, 24), MkFloor EmptyTile)
    , ((26, 24), MkFloor EmptyTile)
    , ((27, 24), MkFloor EmptyTile)
    , ((28, 24), MkWall (MkWallShape Vertical))
    , ((29, 24), MkWall (MkWallShape Vertical))
    , ((0, 25), MkWall (MkWallShape Vertical))
    , ((1, 25), MkWall (MkCorner NE))
    , ((2, 25), MkWall (MkWallShape Horizontal))
    , ((3, 25), MkWall (MkCorner SW))
    , ((4, 25), MkFloor EmptyTile)
    , ((5, 25), MkWall (MkWallShape Vertical))
    , ((6, 25), MkWall (MkWallShape Vertical))
    , ((7, 25), MkFloor EmptyTile)
    , ((8, 25), MkWall (MkCorner SE))
    , ((9, 25), MkWall (MkCorner SW))
    , ((10, 25), MkFloor EmptyTile)
    , ((11, 25), MkWall (MkCorner SE))
    , ((12, 25), MkWall (MkWallShape Horizontal))
    , ((13, 25), MkWall (MkWallShape Horizontal))
    , ((14, 25), MkWall (MkWallShape Horizontal))
    , ((15, 25), MkWall (MkWallShape Horizontal))
    , ((16, 25), MkWall (MkWallShape Horizontal))
    , ((17, 25), MkWall (MkWallShape Horizontal))
    , ((18, 25), MkWall (MkCorner SW))
    , ((19, 25), MkFloor EmptyTile)
    , ((20, 25), MkWall (MkCorner SE))
    , ((21, 25), MkWall (MkCorner SW))
    , ((22, 25), MkFloor EmptyTile)
    , ((23, 25), MkWall (MkWallShape Vertical))
    , ((24, 25), MkWall (MkWallShape Vertical))
    , ((25, 25), MkFloor EmptyTile)
    , ((26, 25), MkWall (MkCorner SE))
    , ((27, 25), MkWall (MkWallShape Horizontal))
    , ((28, 25), MkWall (MkCorner NW))
    , ((29, 25), MkWall (MkWallShape Vertical))
    , ((0, 26), MkWall (MkWallShape Vertical))
    , ((1, 26), MkWall (MkCorner SE))
    , ((2, 26), MkWall (MkWallShape Horizontal))
    , ((3, 26), MkWall (MkCorner NW))
    , ((4, 26), MkFloor EmptyTile)
    , ((5, 26), MkWall (MkCorner NE))
    , ((6, 26), MkWall (MkCorner NW))
    , ((7, 26), MkFloor EmptyTile)
    , ((8, 26), MkWall (MkWallShape Vertical))
    , ((9, 26), MkWall (MkWallShape Vertical))
    , ((10, 26), MkFloor EmptyTile)
    , ((11, 26), MkWall (MkCorner NE))
    , ((12, 26), MkWall (MkWallShape Horizontal))
    , ((13, 26), MkWall (MkWallShape Horizontal))
    , ((14, 26), MkWall (MkCorner SW))
    , ((15, 26), MkWall (MkCorner SE))
    , ((16, 26), MkWall (MkWallShape Horizontal))
    , ((17, 26), MkWall (MkWallShape Horizontal))
    , ((18, 26), MkWall (MkCorner NW))
    , ((19, 26), MkFloor EmptyTile)
    , ((20, 26), MkWall (MkWallShape Vertical))
    , ((21, 26), MkWall (MkWallShape Vertical))
    , ((22, 26), MkFloor EmptyTile)
    , ((23, 26), MkWall (MkCorner NE))
    , ((24, 26), MkWall (MkCorner NW))
    , ((25, 26), MkFloor EmptyTile)
    , ((26, 26), MkWall (MkCorner NE))
    , ((27, 26), MkWall (MkWallShape Horizontal))
    , ((28, 26), MkWall (MkCorner SW))
    , ((29, 26), MkWall (MkWallShape Vertical))
    , ((0, 27), MkWall (MkWallShape Vertical))
    , ((1, 27), MkWall (MkWallShape Vertical))
    , ((2, 27), MkFloor EmptyTile)
    , ((3, 27), MkFloor EmptyTile)
    , ((4, 27), MkFloor EmptyTile)
    , ((5, 27), MkFloor EmptyTile)
    , ((6, 27), MkFloor EmptyTile)
    , ((7, 27), MkFloor EmptyTile)
    , ((8, 27), MkWall (MkWallShape Vertical))
    , ((9, 27), MkWall (MkWallShape Vertical))
    , ((10, 27), MkFloor EmptyTile)
    , ((11, 27), MkFloor EmptyTile)
    , ((12, 27), MkFloor EmptyTile)
    , ((13, 27), MkFloor EmptyTile)
    , ((14, 27), MkWall (MkWallShape Vertical))
    , ((15, 27), MkWall (MkWallShape Vertical))
    , ((16, 27), MkFloor EmptyTile)
    , ((17, 27), MkFloor EmptyTile)
    , ((18, 27), MkFloor EmptyTile)
    , ((19, 27), MkFloor EmptyTile)
    , ((20, 27), MkWall (MkWallShape Vertical))
    , ((21, 27), MkWall (MkWallShape Vertical))
    , ((22, 27), MkFloor EmptyTile)
    , ((23, 27), MkFloor EmptyTile)
    , ((24, 27), MkFloor EmptyTile)
    , ((25, 27), MkFloor EmptyTile)
    , ((26, 27), MkFloor EmptyTile)
    , ((27, 27), MkFloor EmptyTile)
    , ((28, 27), MkWall (MkWallShape Vertical))
    , ((29, 27), MkWall (MkWallShape Vertical))
    , ((0, 28), MkWall (MkWallShape Vertical))
    , ((1, 28), MkWall (MkWallShape Vertical))
    , ((2, 28), MkFloor EmptyTile)
    , ((3, 28), MkWall (MkCorner SE))
    , ((4, 28), MkWall (MkWallShape Horizontal))
    , ((5, 28), MkWall (MkWallShape Horizontal))
    , ((6, 28), MkWall (MkWallShape Horizontal))
    , ((7, 28), MkWall (MkWallShape Horizontal))
    , ((8, 28), MkWall (MkCorner NW))
    , ((9, 28), MkWall (MkCorner NE))
    , ((10, 28), MkWall (MkWallShape Horizontal))
    , ((11, 28), MkWall (MkWallShape Horizontal))
    , ((12, 28), MkWall (MkCorner SW))
    , ((13, 28), MkFloor EmptyTile)
    , ((14, 28), MkWall (MkWallShape Vertical))
    , ((15, 28), MkWall (MkWallShape Vertical))
    , ((16, 28), MkFloor EmptyTile)
    , ((17, 28), MkWall (MkCorner SE))
    , ((18, 28), MkWall (MkWallShape Horizontal))
    , ((19, 28), MkWall (MkWallShape Horizontal))
    , ((20, 28), MkWall (MkCorner NW))
    , ((21, 28), MkWall (MkCorner NE))
    , ((22, 28), MkWall (MkWallShape Horizontal))
    , ((23, 28), MkWall (MkWallShape Horizontal))
    , ((24, 28), MkWall (MkWallShape Horizontal))
    , ((25, 28), MkWall (MkWallShape Horizontal))
    , ((26, 28), MkWall (MkCorner SW))
    , ((27, 28), MkFloor EmptyTile)
    , ((28, 28), MkWall (MkWallShape Vertical))
    , ((29, 28), MkWall (MkWallShape Vertical))
    , ((0, 29), MkWall (MkWallShape Vertical))
    , ((1, 29), MkWall (MkWallShape Vertical))
    , ((2, 29), MkFloor EmptyTile)
    , ((3, 29), MkWall (MkCorner NE))
    , ((4, 29), MkWall (MkWallShape Horizontal))
    , ((5, 29), MkWall (MkWallShape Horizontal))
    , ((6, 29), MkWall (MkWallShape Horizontal))
    , ((7, 29), MkWall (MkWallShape Horizontal))
    , ((8, 29), MkWall (MkWallShape Horizontal))
    , ((9, 29), MkWall (MkWallShape Horizontal))
    , ((10, 29), MkWall (MkWallShape Horizontal))
    , ((11, 29), MkWall (MkWallShape Horizontal))
    , ((12, 29), MkWall (MkCorner NW))
    , ((13, 29), MkFloor EmptyTile)
    , ((14, 29), MkWall (MkCorner NE))
    , ((15, 29), MkWall (MkCorner NW))
    , ((16, 29), MkFloor EmptyTile)
    , ((17, 29), MkWall (MkCorner NE))
    , ((18, 29), MkWall (MkWallShape Horizontal))
    , ((19, 29), MkWall (MkWallShape Horizontal))
    , ((20, 29), MkWall (MkWallShape Horizontal))
    , ((21, 29), MkWall (MkWallShape Horizontal))
    , ((22, 29), MkWall (MkWallShape Horizontal))
    , ((23, 29), MkWall (MkWallShape Horizontal))
    , ((24, 29), MkWall (MkWallShape Horizontal))
    , ((25, 29), MkWall (MkWallShape Horizontal))
    , ((26, 29), MkWall (MkCorner NW))
    , ((27, 29), MkFloor EmptyTile)
    , ((28, 29), MkWall (MkWallShape Vertical))
    , ((29, 29), MkWall (MkWallShape Vertical))
    , ((0, 30), MkWall (MkWallShape Vertical))
    , ((1, 30), MkWall (MkWallShape Vertical))
    , ((2, 30), MkFloor EmptyTile)
    , ((3, 30), MkFloor EmptyTile)
    , ((4, 30), MkFloor EmptyTile)
    , ((5, 30), MkFloor EmptyTile)
    , ((6, 30), MkFloor EmptyTile)
    , ((7, 30), MkFloor EmptyTile)
    , ((8, 30), MkFloor EmptyTile)
    , ((9, 30), MkFloor EmptyTile)
    , ((10, 30), MkFloor EmptyTile)
    , ((11, 30), MkFloor EmptyTile)
    , ((12, 30), MkFloor EmptyTile)
    , ((13, 30), MkFloor EmptyTile)
    , ((14, 30), MkFloor EmptyTile)
    , ((15, 30), MkFloor EmptyTile)
    , ((16, 30), MkFloor EmptyTile)
    , ((17, 30), MkFloor EmptyTile)
    , ((18, 30), MkFloor EmptyTile)
    , ((19, 30), MkFloor EmptyTile)
    , ((20, 30), MkFloor EmptyTile)
    , ((21, 30), MkFloor EmptyTile)
    , ((22, 30), MkFloor EmptyTile)
    , ((23, 30), MkFloor EmptyTile)
    , ((24, 30), MkFloor EmptyTile)
    , ((25, 30), MkFloor EmptyTile)
    , ((26, 30), MkFloor EmptyTile)
    , ((27, 30), MkFloor EmptyTile)
    , ((28, 30), MkWall (MkWallShape Vertical))
    , ((29, 30), MkWall (MkWallShape Vertical))
    , ((0, 31), MkWall (MkWallShape Vertical))
    , ((1, 31), MkWall (MkCorner NE))
    , ((2, 31), MkWall (MkWallShape Horizontal))
    , ((3, 31), MkWall (MkWallShape Horizontal))
    , ((4, 31), MkWall (MkWallShape Horizontal))
    , ((5, 31), MkWall (MkWallShape Horizontal))
    , ((6, 31), MkWall (MkWallShape Horizontal))
    , ((7, 31), MkWall (MkWallShape Horizontal))
    , ((8, 31), MkWall (MkWallShape Horizontal))
    , ((9, 31), MkWall (MkWallShape Horizontal))
    , ((10, 31), MkWall (MkWallShape Horizontal))
    , ((11, 31), MkWall (MkWallShape Horizontal))
    , ((12, 31), MkWall (MkWallShape Horizontal))
    , ((13, 31), MkWall (MkWallShape Horizontal))
    , ((14, 31), MkWall (MkWallShape Horizontal))
    , ((15, 31), MkWall (MkWallShape Horizontal))
    , ((16, 31), MkWall (MkWallShape Horizontal))
    , ((17, 31), MkWall (MkWallShape Horizontal))
    , ((18, 31), MkWall (MkWallShape Horizontal))
    , ((19, 31), MkWall (MkWallShape Horizontal))
    , ((20, 31), MkWall (MkWallShape Horizontal))
    , ((21, 31), MkWall (MkWallShape Horizontal))
    , ((22, 31), MkWall (MkWallShape Horizontal))
    , ((23, 31), MkWall (MkWallShape Horizontal))
    , ((24, 31), MkWall (MkWallShape Horizontal))
    , ((25, 31), MkWall (MkWallShape Horizontal))
    , ((26, 31), MkWall (MkWallShape Horizontal))
    , ((27, 31), MkWall (MkWallShape Horizontal))
    , ((28, 31), MkWall (MkCorner NW))
    , ((29, 31), MkWall (MkWallShape Vertical))
    , ((0, 32), MkWall (MkCorner NE))
    , ((1, 32), MkWall (MkWallShape Horizontal))
    , ((2, 32), MkWall (MkWallShape Horizontal))
    , ((3, 32), MkWall (MkWallShape Horizontal))
    , ((4, 32), MkWall (MkWallShape Horizontal))
    , ((5, 32), MkWall (MkWallShape Horizontal))
    , ((6, 32), MkWall (MkWallShape Horizontal))
    , ((7, 32), MkWall (MkWallShape Horizontal))
    , ((8, 32), MkWall (MkWallShape Horizontal))
    , ((9, 32), MkWall (MkWallShape Horizontal))
    , ((10, 32), MkWall (MkWallShape Horizontal))
    , ((11, 32), MkWall (MkWallShape Horizontal))
    , ((12, 32), MkWall (MkWallShape Horizontal))
    , ((13, 32), MkWall (MkWallShape Horizontal))
    , ((14, 32), MkWall (MkWallShape Horizontal))
    , ((15, 32), MkWall (MkWallShape Horizontal))
    , ((16, 32), MkWall (MkWallShape Horizontal))
    , ((17, 32), MkWall (MkWallShape Horizontal))
    , ((18, 32), MkWall (MkWallShape Horizontal))
    , ((19, 32), MkWall (MkWallShape Horizontal))
    , ((20, 32), MkWall (MkWallShape Horizontal))
    , ((21, 32), MkWall (MkWallShape Horizontal))
    , ((22, 32), MkWall (MkWallShape Horizontal))
    , ((23, 32), MkWall (MkWallShape Horizontal))
    , ((24, 32), MkWall (MkWallShape Horizontal))
    , ((25, 32), MkWall (MkWallShape Horizontal))
    , ((26, 32), MkWall (MkWallShape Horizontal))
    , ((27, 32), MkWall (MkWallShape Horizontal))
    , ((28, 32), MkWall (MkWallShape Horizontal))
    , ((29, 32), MkWall (MkCorner NW))
    ]
